// The cast of the congratulations scene: what each character looks like,
// for the bust in Cast.jsx. Order of CAST is the order of the quick cuts.

export const SKIN = "#f7dcc8";
const PALE = "#f8eee8";
const SHIRT = "#f4f3ee";
const SCHOOL = "#2c4a8a";
const BRIDGE = "#8a7b55";

// Gendo and Yui come last, together (PARENTS).
export const CAST = [
  {
    id: "misato",
    jp: "葛城ミサト",
    en: "MISATO KATSURAGI",
    hair: "#4a2c6b",
    style: "long",
    outfit: "#b8192c",
    collar: "#16121a",
    eyes: "#6b3a3a",
    extras: ["cross"],
    glow: "#a77bff",
  },
  {
    id: "asuka",
    jp: "惣流・アスカ・ラングレー",
    en: "ASUKA LANGLEY SORYU",
    hair: "#d8552a",
    style: "asuka",
    outfit: "#f0c43a",
    eyes: "#2f6fd0",
    extras: ["clips"],
    glow: "#ff3d3d",
  },
  {
    id: "rei",
    jp: "綾波レイ",
    en: "REI AYANAMI",
    hair: "#9ab8e8",
    style: "bob",
    outfit: SCHOOL,
    collar: SHIRT,
    eyes: "#d4202f",
    skin: PALE,
    glow: "#6aa8ff",
  },
  {
    id: "kaworu",
    jp: "渚カヲル",
    en: "KAWORU NAGISA",
    hair: "#dcdce6",
    style: "messy",
    outfit: SHIRT,
    collar: SHIRT,
    eyes: "#d4202f",
    skin: PALE,
    glow: "#c9c9ff",
  },
  {
    id: "toji",
    jp: "鈴原トウジ",
    en: "TOJI SUZUHARA",
    hair: "#18181a",
    style: "buzz",
    outfit: "#17171d",
    eyes: "#2a2222",
    extras: ["stripes"],
    glow: "#8cff3a",
  },
  {
    id: "kensuke",
    jp: "相田ケンスケ",
    en: "KENSUKE AIDA",
    hair: "#6b4a2a",
    style: "short",
    outfit: SHIRT,
    collar: SHIRT,
    eyes: "#3a2a1a",
    extras: ["glasses", "freckles"],
    glow: "#ffb347",
  },
  {
    id: "hikari",
    jp: "洞木ヒカリ",
    en: "HIKARI HORAKI",
    hair: "#6b3a22",
    style: "pigtails",
    outfit: SCHOOL,
    collar: SHIRT,
    eyes: "#4a2a1a",
    extras: ["freckles"],
    glow: "#ff9ec4",
  },
  {
    id: "ritsuko",
    jp: "赤木リツコ",
    en: "RITSUKO AKAGI",
    hair: "#ecd590",
    style: "bob",
    outfit: "#f6f6f2",
    collar: "#3a5aa0",
    eyes: "#4a3a2a",
    extras: ["mole", "labcoat"],
    glow: "#ffd23f",
  },
  {
    id: "kaji",
    jp: "加持リョウジ",
    en: "RYOJI KAJI",
    hair: "#3a2a22",
    style: "ponytail",
    outfit: "#dcd6c8",
    collar: "#dcd6c8",
    eyes: "#2a1a14",
    extras: ["tie", "stubble"],
    glow: "#43d6ff",
  },
  {
    id: "maya",
    jp: "伊吹マヤ",
    en: "MAYA IBUKI",
    hair: "#5a3a26",
    style: "short",
    outfit: "#c9ad73",
    eyes: "#3a2a1a",
    glow: "#8cff3a",
  },
  {
    id: "shigeru",
    jp: "青葉シゲル",
    en: "SHIGERU AOBA",
    hair: "#3a2e28",
    style: "longStraight",
    outfit: BRIDGE,
    eyes: "#2a2a2a",
    glow: "#ff8a1f",
  },
  {
    id: "makoto",
    jp: "日向マコト",
    en: "MAKOTO HYUGA",
    hair: "#1e1e22",
    style: "short",
    outfit: BRIDGE,
    eyes: "#2a2a2a",
    extras: ["glasses"],
    glow: "#6aa8ff",
  },
  {
    id: "fuyutsuki",
    jp: "冬月コウゾウ",
    en: "KOZO FUYUTSUKI",
    hair: "#bdbdbd",
    style: "slicked",
    outfit: "#22222a",
    eyes: "#3a3a3a",
    extras: ["lines"],
    glow: "#c6a8ff",
  },
  { id: "penpen", jp: "ペンペン", en: "PEN PEN", penguin: true, glow: "#43d6ff" },
];

export const PARENTS = [
  {
    id: "gendo",
    jp: "碇ゲンドウ",
    en: "GENDO IKARI",
    hair: "#18181a",
    style: "slicked",
    outfit: "#1e1e24",
    eyes: "#1a1a1a",
    extras: ["beard", "shades", "gloves"],
  },
  { id: "yui", jp: "碇ユイ", en: "YUI IKARI", hair: "#4a3022", style: "short", outfit: "#e6ddc6", eyes: "#3a2a1a" },
];

export const SHINJI = {
  id: "shinji",
  jp: "碇シンジ",
  en: "SHINJI IKARI",
  hair: "#33241c",
  style: "messy",
  outfit: SHIRT,
  collar: SHIRT,
  eyes: "#24345e",
};
